### ISSUE TITLE
Upgrade to RN26.1

### ISSUE THREAD

**Issue by wookiem** [bartonhammond/snowflake#100]
Hi @bartonhammond.  I've upgraded to RN26.1 but have only been able to test against iOS.  I haven't tested Android.  I've updated readme.md but someone else will need to complete any additional notes for Android.  

I'm still not familiar with jest and so I wasn't able to resolve the failing test cases.  

I've also included an udpated Parse.js to get around the json issue based on another poster's comments.  However, I'm pretty sure the "catch" use-cases don't work. 

https://github.com/wookiem/snowflake/tree/snowflakeFix

**Comment by bartonhammond** [comment]
Hi @wookiem - if you would make a PR, I can test the android and look into the Jest tests and JSON responses.  

Thanks, again, for taking the time to upgrade.

**Comment by wookiem** [comment]
Yeah, as others have commented, this upgrade was not particularly straightforward.  Thanks for looking at the remaining open issues.

**Comment by bartonhammond** [comment]
Closed w/ release [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha)

Thanks!
