### ISSUE TITLE
Error: evaluating screenPhysicalPixels.width

### ISSUE THREAD

**Issue by DarrylD** [bartonhammond/snowflake#102]
Cloned and ran for android, got this error

![error](https://cloud.githubusercontent.com/assets/1310383/15629605/76ac0030-24eb-11e6-83f7-5bd835d167c8.png)

**Comment by bartonhammond** [comment]
Make sure you are running ```react-native start``` from the correct directory

**Comment by DarrylD** [comment]
😳 the root, correct??
```
Mac-Air:snowflake darryl$ list
.
├── LICENSE
├── README.md
├── android
├── bitrise
├── fastlane
├── index.android.js
├── index.ios.js
├── ios
├── node_modules
├── package.json
└── src

6 directories, 5 files
Mac-Air:snowflake darryl$ react-native start
```

**Comment by bartonhammond** [comment]
Yeah, that looks right.  Not sure what the problem is.  You might try ```rm -rf node_modules``` and then ```npm install```.  Otherwise, I'm not sure.  Sorry...

**Comment by DarrylD** [comment]
my versions:
npm - 3.9.2
node - 5.5.0

I tried to install fresh modules, no dice. I'll keep tinkering. Thx!

**Comment by bartonhammond** [comment]
Rats.

**Comment by bartonhammond** [comment]
What was it?

**Comment by DarrylD** [comment]
Haven't found a solution, will post it when come back to it.

**Comment by Thomsos** [comment]
It seems to be an issue with React-Native, check it out here: https://github.com/facebook/react-native/issues/5963
