### ISSUE TITLE
undefined is not an object (evaluating 'screenPhysicalPixels.width') for android

### ISSUE THREAD

**Issue by senvsen** [bartonhammond/snowflake#104]
snowflake\android\app\build.gradle
compile "com.facebook.react:react-native:0.17.+"   
 →
compile "com.facebook.react:react-native:0.20.+"

**Comment by Anfelroth** [comment]
i have the same issue  

E/ReactNativeJS(10893): undefined is not an object (evaluating 'screenPhysicalPixels.width')
I/ReactNativeJS(10893): 'Failed to print error: ', 'undefined is not an object (evaluating \'RCTSourceCode.getScriptText().\nthen\')'

**Comment by senvsen** [comment]
You change the [snowflake\android\app\build.gradle]file  [compile "com.facebook.react:react-native:0.17.+"] to compile "com.facebook.react:react-native:0.20.+"

**Comment by bartonhammond** [comment]
This should be fixed now w/ the latest release: [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha).  

Be sure to read those release notes!
