### ISSUE TITLE
apsl-react-native-button breaks jest  

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#11]
Fix/merge or open defect on their project

**Comment by 10fingerz** [comment]
Hey, I am having the same problem, did you find a solution / workaround to this issue? 
Thanks, Thomas

**Comment by bartonhammond** [comment]
Fixed w/ [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2)
