### ISSUE TITLE
Bogus actions tests

### ISSUE THREAD

**Issue by sharq1** [bartonhammond/snowflake#112]
Iterations as below don't test anything, as result of `store.dispatch` is tested, which is resolved as true if action it receives as an argument exists.
```
it('should deleteSessionToken', () => {
    const expectedActions = [
      {type: DELETE_TOKEN_REQUEST},
      {type: SESSION_TOKEN_REQUEST},
      {type: SESSION_TOKEN_SUCCESS},
    ];

    const store = mockStore({}, expectedActions);
    return store.dispatch(actions.deleteSessionToken());
});
```

Instead I would expect to have something like this (according to `redux-mock-store` documentation):
```
it('should deleteSessionToken', () => {
    const expectedActions = [
      {type: DELETE_TOKEN_REQUEST},
      {type: SESSION_TOKEN_REQUEST},
      {type: SESSION_TOKEN_SUCCESS},
    ];

    const store = mockStore({}, expectedActions);
    store.dispatch(actions.deleteSessionToken());
    const actions = store.getActions();
    expect(actions).toEqual(expectedActions);
});
```

**Comment by bartonhammond** [comment]
Would you be interested in a providing a PR?

**Comment by bartonhammond** [comment]
Fixed w/ release: [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2.3](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2.3) 

Thanks for pointing out this issue, @sharq1

**Comment by sharq1** [comment]
Thank you for solving this! I didn't respond as my above suggestion wasn't complete and I had other tasks that kept me busy

**Comment by bartonhammond** [comment]
@sharq1 No problem - I appreciate you taking the time to identify the problem and point to the solution.
