### ISSUE TITLE
Update docs for setup w/ Hapi Local

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#115]
Add directions for `ifconfig` and setting the config.js appropriately.

**Comment by bartonhammond** [comment]
Fixed with [https://github.com/bartonhammond/snowflake/releases/tag/0.1.3](https://github.com/bartonhammond/snowflake/releases/tag/0.1.3)

**Comment by infacq** [comment]
do I have to install hapijs manually?

**Comment by bartonhammond** [comment]
When you clone the Snowflake hapi server project, you do the typical `npm
install` and you have a server.  Be sure to do `ipfconfig` to get the ip
address.  This is discussed in the README for both project.  You have to
set up both project to use the ip address.
