### ISSUE TITLE
Reordering README

### ISSUE THREAD

**Issue by omidfi** [bartonhammond/snowflake#126]
Hello, thanks for the great project :+1: 

I had a small point to mention. I guess many users in Github expect to see these as the first things in README files:
- demo (like the screen gifs you already have)
- install notes 

However in Snowflake finding those two items needs lots of scrolling. I suggest to bring them up to the top of README before any notes. I can send a PR if you like the idea.

**Comment by bartonhammond** [comment]
Yeah - If you can make the README more professional and clear, please do
make a PR.  I know all the GIFs are out of date now as I changed out the
"mark" w/ the "snowflake" icon.

Thanks.

**Comment by omidfi** [comment]
Thanks for the reply. Here you go https://github.com/bartonhammond/snowflake/pull/127

**Comment by bartonhammond** [comment]
PR #127 fixes this - Thanks @omidfi
