### ISSUE TITLE
Cannot register with my own Parse server hosting on Amazon

### ISSUE THREAD

**Issue by shic** [bartonhammond/snowflake#128]
I tried to run the app with my parse serve. But got the following error. 
![screen shot 2016-08-23 at 16 37 56](https://cloud.githubusercontent.com/assets/4471626/17896650/bc4973ca-6951-11e6-8c71-c29bac73d327.png)

My parse server works, so the problem maybe the configuration of parse server in app.
The following is my setup:

```javascript
module.exports = {
  PARSE: {
    APP_ID: 'weasyapp',
    REST_API_KEY: 'weasyapp',
    SESSION_TOKEN_KEY: 'SESSION_TOKEN_KEY'
  },

  constructor( token) {
    super(token);
    if (!_.isNull(token) && _.isUndefined(token.sessionToken)) {
      throw 'TokenMissing';
    }
    this._sessionToken =
      _.isNull(token) ?  null :  token.sessionToken.sessionToken;

    this._applicationId = CONFIG.PARSE.APP_ID;
    this._restAPIKey = CONFIG.PARSE.REST_API_KEY;
    this._masterKey = null;

    this.API_BASE_URL= 'MY_IP_HERE';
  }
```

Am I right with the configuration or this app works only with the parse server hosted on Parse.com? Thanks!

**Comment by shic** [comment]
I read from previous issues that this project does not support parse-server. But I am wondering why this project does not support parse-server? What are the differences between the parse hosted on Parse.com with the parse hosted by my own server?

**Comment by bartonhammond** [comment]
Only works for Parse server, running on Parse.com

**Comment by bartonhammond** [comment]
I haven't had the time to look at the `parse-server`.  

If you want to support it, please do and create a PR for snowflake.

I think you would create a `snowflake-parse-server` project for the server side and then update `snowflake` by creating a new `src/lib/Parse-server` that subclasses `Backend`.

**Comment by bartonhammond** [comment]
@shic Any progress w/ `parse-server`?  I can't answer this question as I haven't looked into `parse-server`.  I am willing to helping you address this if you are interested.

>I read from previous issues that this project does not support parse-server. But I am wondering why this project does not support parse-server? What are the differences between the parse hosted on Parse.com with the parse hosted by my own server?

**Comment by bartonhammond** [comment]
@shic Do you have your repo available for me to look at?  I went through the Parse-Server videos today and this is much further along then when I initially looked at it. I was surprised to see 11K Stargazers!  
I would like to work on having Parse-Server as one of the options now.  If you want to contribute your code to a new `snowflake-parse-server` that would be great. Otherwise I'll start addressing this on my own.  Let me know what you think.  
Thanks for bringing this (again) to my attention!

**Comment by shic** [comment]
@bartonhammond I am glad to contribute about the Parse-server. But for now, I am still studying about the integration. I suggest you to check the repo of F8 https://github.com/fbsamples/f8app created by Facebook which is integrated with Parse server, I tried to run it. It works for my parse server. I am studying it.

**Comment by bartonhammond** [comment]
I have no plans, personally, to address this.  If you want to add this functionality, maybe you could consider a solution that hosts the Parse-Server such as [https://www.back4app.com/pricing](https://www.back4app.com/pricing) that has a **free** solution that appears to be sufficient for Snowflakes requirements. A PR that addresses this would be great.
