### ISSUE TITLE
First condition of reducers

### ISSUE THREAD

**Issue by joles86** [bartonhammond/snowflake#130]
Hi,

Can you explain the idea behind doing this in every reducers?

`if (!(state instanceof InitialState)) return initialState.mergeDeep(state);`

Thanks!

**Comment by bartonhammond** [comment]
If the object passed in is not an instance of the Initial State, then
create an instance of initial state.  So this takes effect on the first
call and during the tests.  One of the rules of Redux is you start with and
always have a valid state, even on the first call.

**Comment by joles86** [comment]
Isn't it what `combineReducers` is already doing?

_The resulting reducer calls every child reducer, and gathers their results into a single state object._
http://redux.js.org/docs/api/combineReducers.html

**Comment by bartonhammond** [comment]
When the `combineReducers` is invoked, Redux performs an INIT call, which basically calls each reducer.  During that call, since a `state` is not provided, then the Initial State is defaulted in.

From this page,[http://redux.js.org/docs/basics/Reducers.html](http://redux.js.org/docs/basics/Reducers.html), when the first parameter is not a proper state, you initialize the state.  Note the reference to [https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters)


```
function todoApp(state = initialState, action) {
  // For now, don’t handle any actions
  // and just return the state given to us.
  return state
}
```

From this page [http://redux.js.org/docs/api/combineReducers.html](http://redux.js.org/docs/api/combineReducers.html), in the **Notes** section is this bullet:

>If the state given to it is undefined, it must return the initial state for this specific reducer. According to the previous rule, the initial state must not be undefined either. It is handy to specify it with ES6 optional arguments syntax, but you can also explicitly check the first argument for being undefined.

This is exactly what Snowflake is doing, it sets the initial state when it is not provided using the ES6 optional arguments syntax.

**Comment by joles86** [comment]
True, that's why I was asking about :
`if (!(state instanceof InitialState)) return initialState.mergeDeep(state);`
Since we use the ES6 optional parameter, isn't it useless ?

**Comment by bartonhammond** [comment]
Ah, I see now what you mean - sorry I didn't understand your point clearly - thanks for clarifying.  

That specific line may well indeed not be necessary.  Have you tried removing all of them and seeing if there is any change, ie the app still runs and the tests all past?  If so, please consider making a PR.

**Comment by bartonhammond** [comment]
I was trying to remember why that line may have been added.  

One use case that might have required that line is when the `state` is restored.  Imagine the state was saved at some point, but then the app was upgraded and the "shape" of the initial state has changed.  

It might fail the `instance of` when restored and therefore the need to copy deep to a valid `initialState`.  But right now #91 **Hot loading breaks the app** breaks.  I haven't had the time to address this particular issue.

**Comment by bartonhammond** [comment]
@joles86 - Are you going to make a PR?  I think for now, if you want to validate that removing this line doesn't effect the `npm test` results or the running of the app, that would be a welcomed PR.  Let me know if you plan on addressing this yourself.  Thanks.

**Comment by joles86** [comment]
Yes, I haven't had the time to test it yet. Once tested, I'll do a pull request.

**Comment by bartonhammond** [comment]
That's good.

Be sure to use the latest Snowflake as I added "standardjs"
https://github.com/feross/standard, to standardize all the code.  There are
numerous plugins for the various editors so hopefully it will play well w/
your IDE of choice.  You can confirm your code is structured correctly by
running `npm test` or `npm run format` which will try to `fix` your code if
there are issues.

Good luck, and thanks!

-b

**Comment by joles86** [comment]
I have tested it and it's there for a reason! It's necessary because of Immutable. When serializing a state, it's saved as a plain object. But when deserializing it, it becomes a Map from Immutable instead of a Record. `mergeDeep` is there to reconstruct the Record.

**Comment by bartonhammond** [comment]
Would you mind adding that comment to those reducers?  It's difficult to
remember all there's things.  If you do a PR, I will also regenerate the
docs for github-pages.

Thanks for looking into it!

**Comment by bartonhammond** [comment]
Well, it's not broken and there's no PR so I'm closing. Thanks for the discussion.
