### ISSUE TITLE
How to use nested scene?

### ISSUE THREAD

**Issue by leonardgithub** [bartonhammond/snowflake#136]
please see https://github.com/aksonov/react-native-router-flux/issues/1142
Thanks

**Comment by bartonhammond** [comment]
Is there some problem?  Why did you create this issue?

**Comment by leonardgithub** [comment]
@bartonhammond Hi bartonhammond, I just create this question, but the issue labels can not be set to question. I just want to want how to use nested scene in your snowflake example, i.e. the nested scenes share the UI of their's same parent scene.

**Comment by bartonhammond** [comment]
I'm not sure I understand your question or your intent.  Can you be more specific with what exactly you want?  Thanks

**Comment by leonardgithub** [comment]
@bartonhammond 
Do you know [https://github.com/reactjs/react-router](https://github.com/reactjs/react-router)? With it, the parent component works as a part of the UI of the child component by writing {this.props.children} in parent component. 
But in your example with react-native-router-flux, I do not know how to do like react-router.

**Comment by bartonhammond** [comment]
I don't think I can help you.  This is more a question for `react-native-router-flux`.
