### ISSUE TITLE
Need to pass additional properties to Main/Tabbar to display in Subview

### ISSUE THREAD

**Issue by sudham** [bartonhammond/snowflake#138]
function mapStateToProps(state) {
    return {
        auth: {
            form: {
                isFetching: state.auth.form.isFetching,
                username: state.auth.form.fields.username,
            },
        },
        global: {
            currentState: state.global.currentState,
            showState: state.global.showState,
        },
    };
};

Username here is blank - I need to access the current username here ?

**Comment by bartonhammond** [comment]
Did you use the debugger and look at the `state` object?

**Comment by sudham** [comment]
Thanks -  I added this code in the Main.js file and was able to pass extra params :
function mapStateToProps(state) {
    return {
        auth: {
            form: {
                isFetching: state.auth.form.isFetching,
            },
        },
        global: {
            currentState: state.global.currentState,
            showState: state.global.showState,
            currentUser: state.global.currentUser,
        },
    };
};
 Actions.Subview({
      title: 'Subview',
      currentUser: this.props.global.currentUser,
    });
