### ISSUE TITLE
Why is the tab bat transparent?

### ISSUE THREAD

**Issue by leonardgithub** [bartonhammond/snowflake#139]
Do you know why is the tab bar transparent?
![captura de pantalla de 2016-09-11 21-12-22](https://cloud.githubusercontent.com/assets/5285680/18417524/99f5281e-7865-11e6-8015-3d6f09d197b2.png)

By the way, how can I use my user-defined icon in tab bar? Thanks.

`                <Scene key='Main'
                  title={I18n.t('Snowflake.main')}
                  iconName={"home"}
                  icon={TabIcon}
                  hideNavBar
                  component={Main}
                  initial />`

**Comment by bartonhammond** [comment]
There's nothing in Snowflake that makes the tool bar transparent - please ask the maintainers.  

Also, I don't know how you wrote all the data but I would assume that you didn't properly write a new component that manages it's view and constrains it's size.  You may have to introduce a scroll container if the size of the display is too large.
