### ISSUE TITLE
Android Issue: The development server returned response error code: 500

### ISSUE THREAD

**Issue by nicolabortignon** [bartonhammond/snowflake#141]
Not quite sure why is returning this. 

<img width="1319" alt="screen shot 2016-09-17 at 10 42 10" src="https://cloud.githubusercontent.com/assets/883459/18607116/a9820d26-7cc3-11e6-9958-ebd2e19c7479.png">

I wasn't running the local server side HAPI, but was always working anyway, now it just throw this error at bootstrap. 
iOS works as usual.

ps.: thanks for the great work done on this boilerplate!

**Comment by bartonhammond** [comment]
Please look at release notes.  I changed the format of the SESSION_TOKEN.
Make sure you have that right first.

**Comment by bartonhammond** [comment]
The Release Notes explain that the config file changed.
