### ISSUE TITLE
Memory leaks question

### ISSUE THREAD

**Issue by SimchaShats** [bartonhammond/snowflake#142]
Sorry for newby question, but can someone please explain to me if I'm wrong? Every time when we call action that has link to BackendFactory it's create new object of Hapi object with all functions inside it, and this object return some value that we are using after it like this: 
```
BackendFactory().login({
      username: username,
      password: password
    })
```
So this way every time we are creating closure of Hapi object for every function that uses BackendFactory that uses it, and garbage collector can't clean this because we are saving information from this to redux... The same thing with AppAuthToken class... Am I wrong?

**Comment by bartonhammond** [comment]
Good catch!  Would you mind converting the code into a "Singleton" pattern and create a PR?  I'd appreciate it.

**Comment by SimchaShats** [comment]
Hi, I will try to do it on friday... if I will have time :) thanks...

**Comment by bartonhammond** [comment]
Thanks, I look forward to it

**Comment by SimchaShats** [comment]
Done, now it in PR

**Comment by bartonhammond** [comment]
Fixed w/ Release [https://github.com/bartonhammond/snowflake/releases/tag/0.1.10b](https://github.com/bartonhammond/snowflake/releases/tag/0.1.10b)

**Comment by ckleo** [comment]
Please note that extra care needs to be taken after "singleton" is applied to backend  - e.g. if backend instance is cached before authentication being made, the subsequent backend calls might not carry the token returned from authentication.
