### ISSUE TITLE
Initial State in Snowflake.js

### ISSUE THREAD

**Issue by Lokesh235** [bartonhammond/snowflake#147]
Hi,

Can you explain what is the need of constructing all Initial states in getInitialState() function and pass it to configureStore? What i see in all reducers each has its own individual state which is combined by combineReducer and ultimately doing the same as getInitialState() in snowflake.js. I tried after removing this function and app is still running. So it would be great if you tell the purpose of doing getInitialState() in snowflake.js

**Comment by bartonhammond** [comment]
Why don't you make a PR so I can understand exactly what code you're removing?

**Comment by Lokesh235** [comment]
PR made. Please check. I asked this question just to understand the purpose behind the code. :)

**Comment by bartonhammond** [comment]
@Lokesh235 You didn't make a PR.  I think you made a change to your fork of Snowflake.  Now you have to create a PR, see [https://help.github.com/articles/creating-a-pull-request/](https://help.github.com/articles/creating-a-pull-request/)

**Comment by bartonhammond** [comment]
No PR.
