### ISSUE TITLE
Graphics - App Icons, splash, etc for iOS and Android - need help!!

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#149]
Anyone know how to create the required graphics for iOS and Android?  For example, on iTunesConnect I need an app icon with this description:

>This icon will be used on the App Store and must be in the JPG or PNG format, with a minimum resolution of at least 72 DPI, and in the RGB color space. It must not contain layers or rounded corners.

I just want a Snowflake image that can be used for all the required graphics.

Thanks!

**Comment by rbmedia** [comment]
I used in the past http://ticons.fokkezb.nl. to generate the different size from an original file (2048 x 2048 px)

**Comment by bartonhammond** [comment]
Yeah @rbmedia I'm aware of that.  My problem is the original artwork that's used for input, mine is just awful...

**Comment by rbmedia** [comment]
so you need a nice snowflake logo (vectorial would be the best).

**Comment by bartonhammond** [comment]
Yes - a simple snowflake that I can generate all the required images from.  I thought I was going to be ok w/ what I currently have but when I tried to upload my `src/images/Snowflake-1024.png` in iTunesConnect -> Prepare for Submission->General App Information->App Icon, I get this error: `Images can't contain alpha channels or transparencies`.   I don't understand why my current images work w/in XCode but then I need something different for iTunesConnect.

**Comment by rbmedia** [comment]
I see that you have a transparent background, this must be the issue.

**Comment by bartonhammond** [comment]
The message wasn't specific - but in either case, I'm not good at graphics at all!

**Comment by rbmedia** [comment]
![snowflake-1024-w](https://cloud.githubusercontent.com/assets/4646826/18922473/0d15cc68-85a9-11e6-9c2b-09ba35c5ca7e.png)

the file above has no transparency
if you can wait a week, I could send you a couple of snowflakes (I am a graphic designer, or was one, before beginning to code)

**Comment by bartonhammond** [comment]
Wow!  Yes, I can wait.  I really appreciate this.

**Comment by rbmedia** [comment]
OK, noted, I come back to you next week!

**Comment by bartonhammond** [comment]
That must have been the problem, I was able to upload this version.  Thanks
again.

**Comment by bartonhammond** [comment]
@rbmedia - Are you still going to create a new Snowflake image?  Otherwise I'll use the one that you fixed here.

**Comment by rbmedia** [comment]
Yes, I will send it to you tomorrow!

Granada 85
11140 Conil de la Fra.
Spain
+34 689 307 639


Oppenhoffallee 80
52066 Aachen - Germany
+49 241 400 85384
www.remiblot.com

2016-10-04 19:33 GMT+02:00 Barton Hammond <notifications@github.com>:

**Comment by bartonhammond** [comment]
Super!  Thanks

**Comment by rbmedia** [comment]
![snowflake](https://cloud.githubusercontent.com/assets/4646826/19122050/1d051e6e-8b29-11e6-92c4-a21972b2d55e.png)

**Comment by rbmedia** [comment]
Something like this?
I kept your original construct, the surrounding shadow is perhaps superfluous as the icons will get their own shadows once generated.

**Comment by bartonhammond** [comment]
Looks great to me!

On Oct 5, 2016 11:29 AM, "rbmedia" <notifications@github.com> wrote:

Something like this?
I kept your original construct, the surrounding shadow is perhaps
superfluous as the icons will get their own shadows once generated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bartonhammond/snowflake/issues/149#issuecomment-251726568>,
or mute the thread

**Comment by bartonhammond** [comment]
Could you change the red lones to blue?  I think that might better convey cold.  Thanks.

**Comment by rbmedia** [comment]
OK, I resend it to you this afternoon.

**Comment by rbmedia** [comment]
![snowflake-blue](https://cloud.githubusercontent.com/assets/4646826/19198136/c2651f40-8cbd-11e6-87fd-258501094fcd.png)

**Comment by rbmedia** [comment]
![snowflake-blue-1](https://cloud.githubusercontent.com/assets/4646826/19198193/11daeb4a-8cbe-11e6-9dfe-731843e47a25.png)

**Comment by bartonhammond** [comment]
Nice, thanks again!

**Comment by rbmedia** [comment]
![snowflake-blue-no-shadow](https://cloud.githubusercontent.com/assets/4646826/19198346/f63f94ac-8cbe-11e6-86f0-58d70c2b0324.png)
![snowflake-blue-1-no-shadow](https://cloud.githubusercontent.com/assets/4646826/19198347/f64eb9f0-8cbe-11e6-8beb-4b7d75204436.png)

**Comment by rbmedia** [comment]
hex colors:
#1994bc - snowflake-blue
#0082c3 - snowflake-blue-1

**Comment by rbmedia** [comment]
nothing to thanks, I am  on the way to release my first app connected to a drupal site.
And  I learned from your work!

**Comment by rbmedia** [comment]
Barton, I can send you the vectorial and layered document. give me an email address and I send it to you

**Comment by bartonhammond** [comment]
Bartonhammond@gmail.com

**Comment by bartonhammond** [comment]
What editor do you use or recommend for this graphic?

**Comment by rbmedia** [comment]
Photoshop and Illustrator for the vectorial image

**Comment by bartonhammond** [comment]
@rbmedia - I finally got back to this and I'm having troubles.  First off, after showing the icons (red vs blue) to some friends, they all liked the red version.

I've updated XCode w/ the results splash images from http://ticons.fokkezb.nl/ and the icons from https://makeappicon.com/ - you can see the `src/images/README.md` for the steps I followed.

So when I use my `Fastlane` setup w/ the command `fastlane ios beta` everything is fine until the `pilot` step which gives me this error:

```
[Transporter Error Output]: ERROR ITMS-90096: "Your binary is not optimized for iPhone 5 - New iPhone apps and app updates submitted must support the 4-inch display on iPhone 5 and must include a launch image referenced in the Info.plist under UILaunchImages with a UILaunchImageSize value set to {320, 568}. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the 'iOS Human Interface Guidelines' at 'https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconsImages/IconsImages.html#//apple_ref/doc/uid/TP40006556-CH14-SW5' and the 'iOS App Programming Guide' at 'https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/App-RelatedResources/App-RelatedResources.html#//apple_ref/doc/uid/TP40007072-CH6-SW12'."
[15:01:16]: Transporter transfer failed.
```
I've updated the project.  In the `src/images` I've kept the zip files that I had obtained from the above resources.  You can se

Would you be able to help me figure out what I am missing?  I'd really appreciate it.  I've messed something up with the images but can't figure out what's different.  This XCode stuff really confuses me.

**Comment by bartonhammond** [comment]
Argh - I figured it out - I was missing the image declarationswithin `/ios/snowflake/Images.xcassets/LaunchImage.launchimage/Contents.json`
