### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [bartonhammond/snowflake#151]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by bartonhammond** [comment]
Sure - as long as it doesn't break everyone that doesn't want to use the plugin.

**Comment by amilajack** [comment]
It's pretty stable. It's currently being used by https://github.com/chentsulin/electron-react-boilerplate, a project that I am a core contributor of. So far we haven't had any issues. Maybe we can add this to a prerelease for people that want to try it out and test it?

**Comment by bartonhammond** [comment]
That sounds good, having a pre-release.  What do you need from me?  I've no experience w/ a pre-release.

**Comment by amilajack** [comment]
https://github.com/sindresorhus/np makes that super easy!

**Comment by amilajack** [comment]
Also I don't have npm publishing permission so I need you to publish the prerelease

**Comment by bartonhammond** [comment]
i'll do this manually.  so when you make a PR, does that become the
pre-release?

**Comment by amilajack** [comment]
Yup! So I'll merge into the `dev-master` and you can create a prerelease from that branch.

**Comment by bartonhammond** [comment]
Please provide instructions on how to use it - is there a site that
explains how it can be incorporated into different editors?  For example, I
use emacs.

**Comment by bartonhammond** [comment]
Also, does this have conflict w/ the StandardJS rules?

**Comment by amilajack** [comment]
I haven't used StandardJS before. As long as eslint plugins can be added to this project, it should be fine.

**Comment by amilajack** [comment]
Standard can actually be installed as an eslint plugin:

https://github.com/feross/eslint-config-standard

And by migrating to eslint, we can take advantage of its plugin ecosystem, which is pretty ince.

**Comment by bartonhammond** [comment]
Pardon my ignorance, but what is it a plug in to?

**Comment by amilajack** [comment]
`eslint-config-standard` is a plugin for `eslint` that makes standard rules compat with eslint.

**Comment by bartonhammond** [comment]
So how is eslint being used?

**Comment by amilajack** [comment]
We can run eslint with an npm script:

```
scripts: {
  "lint": "eslint ."
}
```

**Comment by amilajack** [comment]
Closing, as the PR for this has been made
