### ISSUE TITLE
Build fails on npm 3.10.9/xcode 8.0

### ISSUE THREAD

**Issue by jshumakerpruitt** [bartonhammond/snowflake#152]
I can create and run projects with `react-native init`, but build fails with snowflake.  

Steps to reproduce:

`git clone https://github.com/bartonhammond/snowflake`  

`cd snowflake`  

`npm install`  

`cp src/lib/config.example.js src/lib/config.js`  

`react-native run-ios`    

```
The following build commands failed:
    CompileC /Users/js/code/mobile/snowflake/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/snowflake.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/snowflake.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Possibly related issue: https://github.com/facebook/react-native/issues/7308

**Comment by bartonhammond** [comment]
Did you try any of the resolutions suggested such as `react-native upgrade` or checking port 8081?

I'm not at a place where I can easily upgrade to XCode 8.

**Comment by zekedran** [comment]
`react-native-upgrade` didn't help;
I changed the Scheme to `React` in Xcode 8
and finally everything compiled without errors.

I got the packager running at 8081, but `run-ios` still fails

**Comment by alexissmirnov** [comment]
In xcode project, find 2 occurences of calls to `SecRandomCopyBytes`, add handling of the output value:

```
int err = SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
  if(err != noErr)
    @throw [NSException exceptionWithName:@"..." reason:@"..." userInfo:nil];
```

**Comment by amilajack** [comment]
Is there a reason why this project is still using `0.32.0`?

**Comment by jshumakerpruitt** [comment]
@alexissmirnov Thanks. Upgrading to 0.35.0 worked.

**Comment by amilajack** [comment]
Worked for me as well

**Comment by bartonhammond** [comment]
Nope, just haven't upgraded.

**Comment by bartonhammond** [comment]
Please upgrade Snowflake: https://github.com/bartonhammond/snowflake/releases/tag/0.2.1

I'm closing for now as Snowflake appears to be running correctly on both Android and iOS
