### ISSUE TITLE
Continue to show tabs when navigating to sub views

### ISSUE THREAD

**Issue by geekyme** [bartonhammond/snowflake#153]
I would like to build a flow like this: Clicking an item in the `TabBar` will open up a scene with possible nested scenes. Then navigating to those nested scenes do not hide `TabBar`. 

You have a scene with a sub-scene already here: 

<img width="373" alt="screen shot 2016-10-17 at 1 03 09 pm" src="https://cloud.githubusercontent.com/assets/977460/19425839/18f1ff1e-946a-11e6-888a-64948276ddbf.png">

How do I make it such that clicking on 'Navigate to SubView' will not hide the tab bar?

<img width="387" alt="screen shot 2016-10-17 at 1 04 55 pm" src="https://cloud.githubusercontent.com/assets/977460/19425871/5cb62612-946a-11e6-9674-1b30ac9a0c98.png">

**Comment by geekyme** [comment]
It looks like I'm able to do it when I nest `Subview` inside the scene for 'Main'. But not sure is this right? the `hideNavBar` option also appears to not work on the nested scene. 

```
<Scene key='Tabbar'
                tabs
                hideNavBar
                tabBarStyle={styles.tabBar}
                default='MainFlow'>
                <Scene key='Logout'
                  title={I18n.t('Snowflake.logout')}
                  icon={TabIcon}
                  iconName={"sign-out"}
                  hideNavBar
                  component={Logout} />

                <Scene
                  key='MainFlow'
                  title={I18n.t('Snowflake.main')}
                  iconName={"home"}
                  icon={TabIcon}
                  initial
                >
                  <Scene key='Main'
                    hideNavBar
                    initial
                    component={Main} />
                  <Scene key='Subview'
                    hideNavBar
                    component={Subview} />
                </Scene>

                <Scene key='Profile'
                  title={I18n.t('Snowflake.profile')}
                  icon={TabIcon}
                  iconName={"gear"}
                  hideNavBar
                  component={Profile} />
              </Scene>
```

<img width="375" alt="screen shot 2016-10-17 at 1 01 07 pm" src="https://cloud.githubusercontent.com/assets/977460/19425815/d2d30bd6-9469-11e6-9aac-35e88ed99a01.png">

**Comment by bartonhammond** [comment]
I don't know if it's `right` but if it behaves the way you want, then I'd say `go for it`.
