### ISSUE TITLE
PR: Add support for `reactotron`

### ISSUE THREAD

**Issue by amilajack** [bartonhammond/snowflake#157]
[reactotron](https://github.com/reactotron/reactotron) seems like a really promising way of monitoring the development workflow. Would a PR for it be welcome?

**Comment by bartonhammond** [comment]
Interesting - welcomed as long as integrated w/ Redux.

**Comment by bartonhammond** [comment]
Do you plan on making a PR?

**Comment by amilajack** [comment]
Sorry for the delay. I haven't had the time to do this yet.
