### ISSUE TITLE
Password Pattern 

### ISSUE THREAD

**Issue by iSamuelBarney** [bartonhammond/snowflake#167]
What is the best way to disable this at least temporarily. We have an existing user base that didn't set passwords on this pattern I want to allow old passwords before I turn the pattern that's included back on.

**Comment by bartonhammond** [comment]
To start, you could update the `src/reducers/auth/authReducer.js` and remove the case `ON_AUTH_FORM_FIELD_CHANGE`, by default the reducer will return the current state if there is no match on the key.  You would do the same removal with `src/reducers/profile/profileReducer.js` and remove the case `ON_PROFILE_FORM_FIELD_CHANGE`.

**Comment by iSamuelBarney** [comment]
thnx that worked
