### ISSUE TITLE
npm i fails

### ISSUE THREAD

**Issue by QuantumInformation** [bartonhammond/snowflake#17]
I can't run `npm i` because of this:

`apsl-react-native-button": "git@github.com:bartonhammond/react-native-button.git",`

npm ERR! Command failed: git clone --template=/Users/nikos/.npm/_git-remotes/_templates --mirror ssh://git@github.com/bartonhammond/react-native-button.git

**Comment by bartonhammond** [comment]
Not sure why - I cloned snowflake earlier today and didn't have a problem.  You might have to clear your npm cache.

**Comment by QuantumInformation** [comment]
Cache clean didn't help, might be cause I force all npm i to go through ssl

**Comment by bartonhammond** [comment]
Fixed with https://github.com/bartonhammond/snowflake/releases/tag/0.0.5

**Comment by QuantumInformation** [comment]
thanks!
