### ISSUE TITLE
Session Token Json not Saved Properly

### ISSUE THREAD

**Issue by olovphp** [bartonhammond/snowflake#170]
I noticed that after logging in, the json response is passed to `appAuthToken.storeSessionToken` which seems to be expecting the session token as a string. Please see screengrabs below.

![snowflake-bug-report-2](https://cloud.githubusercontent.com/assets/6040727/20520544/876b6b70-b0a7-11e6-9517-7b0531f1157b.PNG)

![snowflake-bug-report](https://cloud.githubusercontent.com/assets/6040727/20520543/8765ae60-b0a7-11e6-8644-77bee3e2397b.PNG)

**Comment by bartonhammond** [comment]
No - it's not expecting a string, it's expecting an object

<img width="884" alt="screen shot 2016-11-23 at 2 26 08 pm" src="https://cloud.githubusercontent.com/assets/1282364/20577643/e3d8ee78-b188-11e6-83ad-42199da9b453.png">

**Comment by olovphp** [comment]
Sorry for the false alarm! Don't know how I missed this! Thanks.

![snowflake-capture](https://cloud.githubusercontent.com/assets/6040727/20593087/45f74f7a-b231-11e6-88de-47317ac07463.PNG)
