### ISSUE TITLE
unable to resolve class com.android.build.OutputFile

### ISSUE THREAD

**Issue by shaweiguo** [bartonhammond/snowflake#171]
Here's what I'm seeing after run react-native run-android:
build file 'D:\react-native-starter-app\android\app\build.gradle': 3: unable to resolve class com.android.build.OutputFile
@ line 3, column 1.
import com.android.build.OutputFile
^

1 error

**Comment by siemiatj** [comment]
This should go away after Snowflake is updated to 0.42.1

**Comment by bartonhammond** [comment]
Please upgrade to https://github.com/bartonhammond/snowflake/releases/tag/0.2.1
