### ISSUE TITLE
Typo on line 261 of src/lib/Parse.js

### ISSUE THREAD

**Issue by iwoork** [bartonhammond/snowflake#173]
There's a typo on line 261 of Parse.js

`reqOpts.headers['X-Parse-Master-Key'] = this.masterKey`

should be:

`reqOpts.headers['X-Parse-Master-Key'] = this._masterKey`

**Comment by wookiem** [comment]
I just submitted a PR to remove masterKey from parse.js per https://github.com/bartonhammond/snowflake/issues/165

**Comment by iSamuelBarney** [comment]
Yea @iwoork make sure your not using the masterkey

**Comment by bartonhammond** [comment]
Fixed w/ release https://github.com/bartonhammond/snowflake/releases/tag/0.2.0-c
