### ISSUE TITLE
Apple Mach-O Linker (Id) Error Linker command failed with exit code 1 

### ISSUE THREAD

**Issue by iSamuelBarney** [bartonhammond/snowflake#175]
Ld /Users/---/Library/Developer/Xcode/DerivedData/---/Build/Intermediates/---.build/Release-iphoneos/snowflakeTests.build/Objects-normal/arm64/snowflakeTests normal arm64
    cd /Volumes/LaCie/---/snowflake/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.2
    export PATH=---

ld: file not found: /Users/---/Library/Developer/Xcode/DerivedData/---/Build/Products/Release-iphoneos/snowflake.app/snowflake
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have gone through like 10 different build fail errors and fixed all but this one. How do I build snowflake from xcode successfully to run on a connected iphone? Seems like maybe something simple I'm missing but I have no idea.

**Comment by bartonhammond** [comment]
You might want to consider doing this through the Apple process supported by [Fastlane](https://fastlane.tools/) which is working in Snowflake.  

You would have to install and setup Fastlane for your Mac which would get your Apple ID and Bundler ID.  I assume you have a Developers Account w/ Apple.

Then you would use the [Match](https://github.com/fastlane/fastlane/tree/master/match) to establish your Certs on a **private** GitHub repository.  

Look at the `fastlane/Fastfile` and you will see the following section which is the `fastlane ios beta`:
```
lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "snowflake",
        project: "./ios/snowflake.xcodeproj"
        ) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```
When you run `fastlane ios beta` the above code will pull in your certs from your private repo w/ `match`, build the app with `gym` and deploy it to **Testflight** via `pilot`.

I had a lot of trouble trying to do all this manually and when I converted it to **Fastlane** it went smooth as butter.

You will then use **iTunesConnect** and then within **My Apps** you will see your app ready for install either for **internal** or **external** users.

I realize it's a little overwhelming, at least for me, to start using the Apple eco system for installing an app but believe me, once you get the Fastlane script working, it's a fantastic time saver.

**Comment by iSamuelBarney** [comment]
I will give it a shot thanks @bartonhammond
