### ISSUE TITLE
How to change splash screen?

### ISSUE THREAD

**Issue by iSamuelBarney** [bartonhammond/snowflake#176]
![image1](https://cloud.githubusercontent.com/assets/6247986/21483257/c0abe2b8-cb44-11e6-831c-aa2da9464624.PNG)

How do I edit this splash screen? I'm guessing android has the same screen but I haven't checked yet. This isn't in snowflake.js or any other file in /src dir that I can see at-least. Any help would be awesome.

**Comment by jamesreilly5** [comment]
The file you're looking for is at "ios/snowflake/Base.lproj/LaunchScreen.xib", search for the text text="snowflake". I haven't looked at Android yet ;)

**Comment by siemiatj** [comment]
Can we close this @bartonhammond ?

**Comment by bartonhammond** [comment]
Answered by @jamesreilly5 - thanks!
