### ISSUE TITLE
How to do a staging/production release?

### ISSUE THREAD

**Issue by iwoork** [bartonhammond/snowflake#177]
I've tried running my app on my device by using the XCode's build tool. App gets successfully installed on my phone but just gets stucked on the splash screen and seems to be connecting to localhost:8081 (and xip.io) when I tried to listen to the network requests.

Is there a configuration/setting that I need to run together with the build?

Thanks

**Comment by bartonhammond** [comment]
I don't put my app on my iOS device in that manner.  Instead I use Fastlane and submit the app to the iConnect TestFlight and load from there.  The `Fastlane` directory in Snowflake works with the command `fastlane ios beta` which submits to TestFlight. It depends on setting up **Match** first.  You need to read through the Fastlane docs - it's quite easy given now for that Snowflake uses it.
