### ISSUE TITLE
Is Snowflake still active?

### ISSUE THREAD

**Issue by Un3qual** [bartonhammond/snowflake#178]

**Comment by bartonhammond** [comment]
I'm  not able to work actively on Snowflake.  If a PR is created, I would
merge, but that is about the  most I can do at this time.  If anyone wants
to take it over, I would like that.

**Comment by siemiatj** [comment]
I'd love to but just started with RN, so need some time to get familiar with it.

**Comment by bartonhammond** [comment]
Hi Kuba,

Let me know if I can help.  I've tried to document everything I've done -
it might not be exhaustive but it should help you.  Be sure to look at
http://bartonhammond.github.io/snowflake/snowflake.js.html for the code
documentation - as to the project it's all in the
https://github.com/bartonhammond/snowflake page.

You might want to think about upgrading the project to the newest release
of RN.  It's a little tedious sometimes 'cause the iOS and Android code
includes numerous add ons that need to stay but when doing the
'react-native upgrade' if you're not careful, they will be removed during
the upgrade.  The upgrade allows one to look at the diffs to help manage
this.  When I do an upgrade, I look at the diffs and use this "diff" option
and manually make the changes unless there's just too many.  If I allow the
upgrade to make the modifications, I have to have taken note what changes
were removed.  It is a good way to learn about RN as when the upgrade to
the native portions are complete, you still need to consider the impact of
upgrading w/ Jest.  It sometimes takes a lot of work to do this.  But if
you're going to learn RN, it's something you'll have to learn eventually.

Here's a couple of links that might help you make the process easier:
https://blog.chendry.org/2016/01/09/react-native-upgrade-checklist.html
https://hashnode.com/post/upgrading-react-native-in-an-existing-project-ciqg696ub0hceaj53wmweggap
https://github.com/tjunnone/npm-check-updates

Good luck!

Barton

**Comment by siemiatj** [comment]
I successfully updated my local project to latest RN ( I think it's 0.41.2) so I should have a PR soon.

**Comment by bartonhammond** [comment]
That would be great!  I look forward to it..

**Comment by bartonhammond** [comment]
Many thanks, again, @siemiatj - I really appreciate your efforts.  Snowflake now has 25 contributors and I am thankful for everyone's contribution.  As long as there is interest in Snowflake and people want to contribute, I will stay involved and manage the PR merges.

Again, thanks!

**Comment by austinksmith** [comment]
@bartonhammond Send me an email sometime, I don't mind stepping in and helping clean this up for you given your situation. I've reached a pretty good place with my hamsters.js project and need something else to look at in my free time.
