### ISSUE TITLE
[Feature request] Comms

### ISSUE THREAD

**Issue by QuantumInformation** [bartonhammond/snowflake#18]
Hi can we have some public forum to discuss with others that are using this? Maybe we could add one to discord reactiflux or glitter?

If not I'm happy to use issues here)

**Comment by bartonhammond** [comment]
I've been using slack.com w/ some other products and it has a free evaluation but they expect at sometime to pay.  Have you experience with discord?

discord doesn't appeal to me - not much in to 'talking' 

I do like what I see in glitter.  What is your experience with it?  I've never used it.

**Comment by bartonhammond** [comment]
btw, just to be clear, this looks good: [https://gitter.im/](https://gitter.im/)

Any experience?

**Comment by bartonhammond** [comment]
Let me know if you are contacted.  I'm trying gitter out

**Comment by bartonhammond** [comment]
@QuantumInformation Gitter seems fine for now - Thanks for thinking about this and suggesting gitter.
