### ISSUE TITLE
Missing dependency whatwg-fetch

### ISSUE THREAD

**Issue by eduardomoroni** [bartonhammond/snowflake#180]
When I tried to run `npm install` I got 
![image](https://cloud.githubusercontent.com/assets/823150/22697777/aa01176a-ed39-11e6-9a6b-243c150f647e.png)

The issue is solved simply running `npm install whatwg-fetch@^1.0.0 --save-dev` or adding `"whatwg-fetch": "^1.1.1"` to package.json, I tried to send a PR but I wasn't able to do so.

**Comment by bartonhammond** [comment]
With upgrade to Snowflake release https://github.com/bartonhammond/snowflake/releases/tag/0.2.1 , this does not occur.  Thanks for looking at Snowflake and contributing.
