### ISSUE TITLE
Renaming app from snowflake to dist name?

### ISSUE THREAD

**Issue by iSamuelBarney** [bartonhammond/snowflake#181]
I am running into errors and issues when trying to change the app name for xcode specifically. Does anyone have advice or guide on how to change the executable/appName from snowflake to the actual app that I want on the app store?

**Comment by iSamuelBarney** [comment]
Note: I have been able to change the display name & icons with no issues, just not the executable name.

**Comment by iSamuelBarney** [comment]
Solved: just create a new project react-native init... and did it from scratch RIP snowflake project.

**Comment by bartonhammond** [comment]
I think that's a good solution!  Thanks...
