### ISSUE TITLE
Few queries regarding the backend

### ISSUE THREAD

**Issue by srinivasdamam** [bartonhammond/snowflake#196]
Is there any reason why backend logic was put in `src/lib` folder as backend functions increase.
Also will there files be wrapped in the `.apk` file since they are inside the `src` folder.
Can we use express with this ? ideally backend should be in another repo right ?

**Comment by bartonhammond** [comment]
There is no `backend` logic in Snowflake.  There is `client` code that makes API calls to the server.  There are two server implementations: Parse Server & Hapi Server.  

If you want to do Express, you would have a server implementation similar to Parse & Hapi and in the `src/lib` you would have a class similar to the either the `parse` or `hapi` cient code.

If you do make a Snowflake Express server and client code, make a PR and I'll bring it in.

Good luck
