### ISSUE TITLE
there is no config.js file or config folder file in the same folder(src/lib). 

### ISSUE THREAD

**Issue by debayan-btcny** [bartonhammond/snowflake#197]
https://github.com/bartonhammond/snowflake/blob/c82c02f538ec06894b98220cb69b4bbcd8f8a046/src/lib/AppAuthToken.js#L15

**Comment by aditya-vaddi** [comment]
Is it fixed? I am getting the same error

**Comment by bartonhammond** [comment]
Be sure to read the instructions for the client, you need to:

> Copy the src/lib/config.example.js to src/lib/config.js.
