### ISSUE TITLE
upgrading to 0.16 and babel 6 ?

### ISSUE THREAD

**Issue by bsy** [bartonhammond/snowflake#21]
Just curious if you're working on upgrading to react native 0.16 and babel 6...

**Comment by bartonhammond** [comment]
Not at this time, but probably soon

**Comment by QuantumInformation** [comment]
@bsy or raise a PR and tests as an exercise for the user.

**Comment by bsy** [comment]
planning on submitting a PR if i get time this weekend

**Comment by QuantumInformation** [comment]
Cheers thx!

¯\_(ツ)_/¯

**Comment by bartonhammond** [comment]
After working all day on this and having way too many issues w/ iOS and Babel I'm going to wait.

**Comment by bartonhammond** [comment]
Starting on this tomorrow, Dec 21

**Comment by bsy** [comment]
Awesome, I haven't had time to jump on this just yet.  Thanks!

--ben

**Comment by bartonhammond** [comment]
fixed with release [0.0.8] (https://github.com/bartonhammond/snowflake/releases/tag/0.0.8)

**Comment by bsy** [comment]
:+1:

**Comment by bsy** [comment]
@bartonhammond getting some test failures locally after a fresh `npm install` for the following:
FAIL  src/components/__tests__/Header-test.js 
FAIL  src/components/__tests__/ItemCheckbox-test.js 
FAIL  src/components/__tests__/FormButton-test.js 
FAIL  src/components/__tests__/LoginForm-test.js 
FAIL  src/components/__tests__/Header-test.js 

`Error: Failed to get mock metadata: /Users/ben/Code/reactnative/snowflake/node_modules/react/lib/canDefineProperty.js`

**Comment by bartonhammond** [comment]
The JSX tests don't work yet - I created issue #29 and now updated the release notes: [https://github.com/bartonhammond/snowflake/releases/tag/0.0.8](https://github.com/bartonhammond/snowflake/releases/tag/0.0.8)
