### ISSUE TITLE
Research Immutable.js fromJS when hot loading

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#22]
Open issue if doesn't work

**Comment by larubbio** [comment]
I switched my app from immutable to seamless since loading state I had to completely reconstruct the state.  Immutable would deserialize to different objects than I serialized if I used fromJS.

**Comment by bartonhammond** [comment]
Not sure I want to exchange Immutable for seamless.

**Comment by bartonhammond** [comment]
Not supporting this any longer
