### ISSUE TITLE
Android signing issues

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#23]
One note, if you generate the Android signing files from code it'll generate a new signing file for every build
Which means that if you have the app installed on your Android device you won't be able to update to a new version
It'll be treated as a separate app, or the install will be rejected
Unless you uninstall the already installed version first
Code signing for android is even worse than for iOS
Because there's no way of regenerating the same keystore
If you lose it you won't be able to push an update to Play Store
We had this issue once, and the only solution is to upload the new version as a completely new app..
We researched this for days, as we didn't believe that there's no other way
But we found no other solution, even after contacting Google
So the keystore file is really really important in case of Android
At least when you publish to Google play store

**Comment by larubbio** [comment]
bitrise now has a sign-apk step so you can upload your key and use that to sign the app.  This means you can get rid of the second build.gradle, the workflow steps to copy it and the step to create the key.

**Comment by bartonhammond** [comment]
Can you do a PR?

**Comment by larubbio** [comment]
I create PR #76 It was a manual merge of the bitrise.yml that works for my project (which has now diverged too much from your repo to actually be useful as a base for pull requests.)

It should work if you drop it in, but some tweaks may be needed.  I don't think it is something I can actually test.

**Comment by bartonhammond** [comment]
Thanks @larubbio !  I'll look at this later in the afternoon

**Comment by austynpember** [comment]
I am really having trouble with this part of getting snowflake to build from bitrise. What exactly do we put in the secret variables for android?

**Comment by bartonhammond** [comment]
In your BitRise `Secret Env Vars` you should have the following assuming you used the default values when building the certificate.

- SNOWFLAKE_RELEASE_STORE_FILE = my-release-key.keystore
- SNOWFLAKE_RELEASE_KEY_ALIAS = my-key-alias
- SNOWFLAKE_RELEASE_STORE_PASSWORD = whatever password you provided for the store
- SNOWFLAKE_RELEASE_KEY_PASSWORD = whatever password you provided for the release
- PARSE_APP_ID = If you're using PARSE, enter it's APP ID
- PARSE_REST_API_KEY - If you're using PARSE, enter the REST API Key

**Comment by austynpember** [comment]
I appreciate your response ~
That makes sense since I never built a certificate. I followed your youtube tutorials and only saw you create a cert for the iOS version. I'm on a linux machine so I couldn't do any of the XCode things. I'm not sure how to do the certificate or the keys for the store/release. (noob here)

**Comment by jhabdas** [comment]
@austynpember you may want to look at Exponent. The goal of the project (one of them, anyway) is never open Xcode or Android Studio. As for those having issues with Bitrise give Buddybuild a try. It was super easy to setup a cross-platform RN app and start distributing test builds whereas Bitrise wasn't. YMMV

https://habd.as/beta-testing-react-native-buddybuild/

**Comment by bartonhammond** [comment]
Not addressing
