### ISSUE TITLE
Jest test fails at "src/components/__tests__/FormButton-test.js"

### ISSUE THREAD

**Issue by jw84** [bartonhammond/snowflake#27]
![image](https://cloud.githubusercontent.com/assets/48764/11970772/ab1feec6-a8e5-11e5-8417-0835c7667be5.png)

Did a git fetch just now and tried to run the test suites but got stopped at FormButton-test.js

```
TypeError: Cannot read property 'topCompositionEnd' of undefined
```

Can someone help explain how the Jest tests work so I can troubleshoot and do a PR?

**Comment by bartonhammond** [comment]
* git clone https://github.com/bartonhammond/snowflake.git
* cd snowflake
* npm install
* npm test

Check your ```node --version```, needs to be 4X something, mine is 4.2.3
Check your ```npm --version```, needs to be 2X something, mine is 2.14.7

**Comment by bartonhammond** [comment]
note that if you upgrade to release 0.0.8 as of today, none of the JSX components work w/ JEST. so rather then ```npm test``` do ```npm test src/reducers```

**Comment by bartonhammond** [comment]
working as designed for now.  - JSX not working until JEST is understood
