### ISSUE TITLE
Unable to build in IOS xCode

### ISSUE THREAD

**Issue by thachp** [bartonhammond/snowflake#32]
I am unable to build snowflake.  I am getting the following error.

![screen shot 2015-12-29 at 1 49 03 pm](https://cloud.githubusercontent.com/assets/1495371/12042764/f49bcadc-ae32-11e5-8a81-06f3901baf92.png)

I suspect it might have something to do with my redux-redux installation, but I confirmed that it is installed in my ./node_module directory.

    uncaught error Error: UnableToResolveError: Unable to resolve module react-redux/native from /Users/thachp/Code/snowflake/src/snowflake.js: Invalid directory /Users/node_modules/react-redux/native

Repro(s)
I followed the instructions in setup.md and made the suggested adjustments in xCode in one of your videos.

I loaded the snowflake project in xCode, hit build

ENV

    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "clean"
    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7

**Comment by bartonhammond** [comment]
What version are you on?  Check the package.json file.

**Comment by thachp** [comment]
"version": "0.0.8",

**Comment by bartonhammond** [comment]
Try meeting me in Gitter - see Badge

**Comment by thachp** [comment]
I pinpointed the problem down to this specific error. "Unable to resolve module react-redux/native."
Though, I do not know what cause the error to appear, but for those who also experienced this error, this is what I have done to fix my problem.  

    - comment out "import { Provider } from 'react-redux/native';" in snowflake.js.
    - build in xCode, expect errors.
    - rm -rf node_modules.
    - npm install
    - restart my mac laptop.
    - uncomment import { Provider } from 'react-redux/native';"
    - rebuild in XCode,

**Comment by alexprice91** [comment]
Have you been able to upgrade yet? I am getting the error `Unable to resolve module redux...`.

I am using redux 4.4.0

**Comment by bartonhammond** [comment]
There is no redux 4.4.0 see [https://github.com/reactjs/redux/blob/master/package.json#L3](https://github.com/reactjs/redux/blob/master/package.json#L3) -it's at ```3.3.1```

**Comment by alexprice91** [comment]
Im sorry, meant to put react-redux: 4.4.0. It turned out being a peer dependency issue. Got it resolved after upgrading to react-native 0.21. Thanks!

**Comment by bartonhammond** [comment]
Good to hear!   How was the upgrade to 0.21?  Any issues?  Did you upgrade both Android and iOS?

**Comment by alexprice91** [comment]
I upgraded both with no issues. I am still pretty new to react-native. My project only has about 10 components and no tests, but everything appears to be working fine.

**Comment by bartonhammond** [comment]
@alexprice91 thanks for the reply.

**Comment by skatpgusskat** [comment]
@bartonhammond same issue, even react-native is 0.21.
react-redux : 4.4.1
redux : 3.3.1
may i get some clue for resolve this problem?
