### ISSUE TITLE
Upgrade react-redux to v.4.0.6 throw UnableToResolveError

### ISSUE THREAD

**Issue by thachp** [bartonhammond/snowflake#33]
Unable to upgrade react-redux to latest version.

    Uncaught error Error: UnableToResolveError: Unable to resolve module react-redux/native.
    Invalid directory /Users/node_modules/react-redux/native

Repro(s)
    In package.json, change "react-redux": "^3.1.0" to "react-redux": "^4.0.5".
    Click Build in XCode

![screen shot 2015-12-29 at 1 49 03 pm](https://cloud.githubusercontent.com/assets/1495371/12042764/f49bcadc-ae32-11e5-8a81-06f3901baf92.png)

ENV

    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm"
    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7

Related to https://github.com/facebook/react-native/issues/4062 and https://github.com/bartonhammond/snowflake/issues/32#

**Comment by bartonhammond** [comment]
Note the docs on React-Redux [https://github.com/rackt/react-redux#react-native](https://github.com/rackt/react-redux#react-native) - We have to stay on 3.x for the time being.

**Comment by joshblour** [comment]
I'm getting the same error even on version "^3.1.0" after upgrading from snowflake "0.0.6" to "0.0.8" ( current master)

**Comment by bartonhammond** [comment]
It builds on a fresh install on my machine and it builds on the CI, Bitrise.  I would confirm that your node_modules is actually at 3.1.0.  You may have to delete the current node_modules/react-redux  and reinstall it.

**Comment by joshblour** [comment]
whoops! i had forgotten to restart the react packager. sorry about that.

**Comment by bartonhammond** [comment]
This is resolved
