### ISSUE TITLE
AWS Cognito Integration

### ISSUE THREAD

**Issue by mikedizon** [bartonhammond/snowflake#36]
https://github.com/morcmarc/react-native-cognito

**Comment by bartonhammond** [comment]
Nice but no thanks

**Comment by mikedizon** [comment]
Now that parse is being shutdown, does that mean this project is obsolete? http://mobile.nytimes.com/blogs/bits/2016/01/28/facebook-to-shut-down-parse-its-platform-for-mobile-developers

**Comment by bartonhammond** [comment]
This project, Snowflake?  No, not at all. Quite the contrary, note that Snowflake is already integrated w/ a OpenShift implementation [https://github.com/bartonhammond/snowflake-hapi-openshift](https://github.com/bartonhammond/snowflake-hapi-openshift).

see the README from Snowflake [https://github.com/bartonhammond/snowflake](https://github.com/bartonhammond/snowflake)

> Note: Snowflake now (Jan 3, 2016) has a choice of servers, either
> The original Parse.com or
> Hapi Server that runs on Openshift and locally.

 I'm running on OpenShift w/ great success.  I have a private project based off of Snowflake and the Hapi-Openshift project and it is a very good solution for a small indie type project.  Free.
