### ISSUE TITLE
Password validation should be more consistent

### ISSUE THREAD

**Issue by Froelund** [bartonhammond/snowflake#40]
Some special characters are accepted, and some aren't. This confuses the user as the rule says that passwords should "have at least a number and a special character and between 6-12 in length".

Example:

This password is accepted: TestTes12*
This password is not accepted: TestTes12?
This password is not accepted: TestTes12±
This password is not accepted: TestTes12(

**Comment by JonasJonny** [comment]
You could improve RegEx pattern.

**Comment by bartonhammond** [comment]
Fixed with [https://github.com/bartonhammond/snowflake/releases/tag/0.1.3](https://github.com/bartonhammond/snowflake/releases/tag/0.1.3) by changing the error message to display the possible special characters that are allowed.
