### ISSUE TITLE
Register Form flickers when already Logged In

### ISSUE THREAD

**Issue by oojr** [bartonhammond/snowflake#42]
When starting the app, the Register Form/Component shows then the state is updated then the Log Out button shows.

**Comment by oojr** [comment]
This is hardly an issue but I think the first screen in this case being the logout screen should be separated out of the Login.js class

**Comment by bartonhammond** [comment]
This should be resolved w/ the latest release [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha)

Please read those notes!
