### ISSUE TITLE
Software keyboard

### ISSUE THREAD

**Issue by blackxored** [bartonhammond/snowflake#49]
Doesn't seem to handle software (virtual) keyboard resizes/scrolls properly.

**Comment by bartonhammond** [comment]
Could you be more specific?  I don't know what you are expecting to see vs what's working now.  Maybe provide a image or something.

**Comment by blackxored** [comment]
When you focus on an input field, and the device's keyboard appears views don't resize. Hopefully makes sense.

**Comment by bartonhammond** [comment]
I don't see this as an issue
