### ISSUE TITLE
Use some CI 

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#5]
Jest tests should run and report available

**Comment by jhabdas** [comment]
@bartonhammond check out my [`.travis.yml`](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/f07854b2f75f0ae6aed2b8297a983a55e6d91ed0/.travis.yml) file for the minimal config to build using Travis. Travis set-up only takes a few minutes and open source repos are [always free](https://travis-ci.com/plans).

**Comment by bartonhammond** [comment]
Thanks @jhabdas for reminding me this is already done w/ the Bitrise.io integration.

**Comment by jhabdas** [comment]
No problem. I think I saw two badges for Bitrise on your README. What made
you choose them?

**Comment by bartonhammond** [comment]
* Free
* Android & iOS Support
* Lots' of integrations 
* Slack.com - their CTO is on there a lot and helped me immensely 
* And being they are starting up, they are more liable to help me

**Comment by jhabdas** [comment]
Thanks for the info, @bartonhammond. Notifying Slack of build status using Webhooks is fairly trivial on just about any CI service I've used. But it sounds like you're leaning towards features and ease-of-use. If you run into CTO person again please put my vote in for an [Exponent](https://exponentjs.com/) integration, and, if needed (it's not clear from the README here), an unauthenticated build log.

**Comment by bartonhammond** [comment]
Don't know what you're referring to 

> Notifying Slack of build status using Webhooks is fairly trivial on just about any CI service I've used. 

I'm talking about being able to 'chat' on https://bitrise.slack.com/

**Comment by jhabdas** [comment]
Given Slack is free for small organizations I'd assumed the differentiator
was in-channel building message with log links.
