### ISSUE TITLE
Cannot build iOS project because of node modules collision

### ISSUE THREAD

**Issue by mikeborozdin** [bartonhammond/snowflake#61]
Hi,

This project is a great effort to make unit tests work for React Native. However, I've run into the same problems as on my own project. The unit tests do run, but the iOS project doesn't build anymore. It happens because of the `react` module in `node_modules`.

When I run the project in Xcode, I receive an error from the React Native packager:

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/mikeborozdin/dev/react-native/snowflake/node_modules/react/node_modules/fbjs/lib/VersionRange.js collides with /Users/mikeborozdin/dev/react-native/snowflake/node_modules/react-native/node_modules/fbjs/lib/VersionRange.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
```

**Comment by bartonhammond** [comment]
Hi @mikeborozdin  - I don't know what to tell you - Here's the screen shot I just took from building snowflake.

I'm assuming that you
* kill any currently running react packagers
* `rm -rf node_modules`
* `npm install npm3`
* `npm3 install`
* `open .`
* XCode -> run

<img width="951" alt="screen shot 2016-02-08 at 3 55 50 pm" src="https://cloud.githubusercontent.com/assets/1282364/12900527/7de9e94a-ce7c-11e5-8e06-f33beb692b8a.png">

**Comment by bartonhammond** [comment]
> ~/projects/MFV/snowflake (master)$ node --version
> v4.2.3
> ~/projects/MFV/snowflake (master)$ npm3 --version
> 3.6.0

**Comment by bartonhammond** [comment]
Note that I also build the iOS app on BitRise so that's two environments successfully building iOS.

**Comment by mikeborozdin** [comment]
Hi @bartonhammond,

Thank you for the rapid response!

I thought getting npm3, as you suggested, would solve the problems, however I ran into a different one:

```
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module ./config from /Users/mikeborozdin/dev/react-native/snowflake/src/lib/BackendFactory.js: Invalid directory /Users/mikeborozdin/dev/react-native/snowflake/src/lib/config
    at ResolutionRequest.js:356:15
    at tryCallOne (/Users/mikeborozdin/dev/react-native/snowflake/node_modules/promise/lib/core.js:37:12)
    at /Users/mikeborozdin/dev/react-native/snowflake/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mikeborozdin/dev/react-native/snowflake/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
```

**Comment by bartonhammond** [comment]
From [https://github.com/bartonhammond/snowflake#setup](https://github.com/bartonhammond/snowflake#setup)

> Copy or move src/lib/config.example.js to src/lib/config.js. Note: you must select one of three options for the backend as shown below:
  backend: {
    parse: false,
    hapiLocal: false,
    hapiRemote: true
  },

Note that if you're using Parse you'll need to fill out those AppId & Rest API key.

**Comment by bartonhammond** [comment]
No news must be good news
