### ISSUE TITLE
Requiring unknown module "./config".

### ISSUE THREAD

**Issue by Pranjal5** [bartonhammond/snowflake#63]
After the js bundle is loaded on my phone. This error appears.
![screenshot_2016-02-12-00-11-34](https://cloud.githubusercontent.com/assets/8691791/12986447/506f09fc-d11d-11e5-9f9c-8c24780e46d2.png)

**Comment by bartonhammond** [comment]
Please refer to the README.md and the section on "Setup"  You have to copy the config.example.js to config.js and make the necessary changes.

**Comment by Pranjal5** [comment]
@bartonhammond Thanks..!! I missed those steps from setup.
