### ISSUE TITLE
I follow the guide,but it can't run correctly

### ISSUE THREAD

**Issue by JerroldLee** [bartonhammond/snowflake#64]
It tips like this:
Unable to resolve module react-redux from snowflake/src/snowflake.js:Invalid directiry /Users/node_modules/react-redux

**Comment by bartonhammond** [comment]
did you 
0) rm -rf node_modules
1) npm install -g npm3
2)npm3 install
3)cp config.example.js config.js
4)edit config to setup your backend
3)react-native run-ios/run-android

Please provide the command line output

**Comment by JonasJonny** [comment]
Unfortunately it could be relative to https://github.com/facebook/react-native/issues/4968.
Clean installation + copy snowflake source is the "best" solution.

**Comment by bartonhammond** [comment]
The latest release should resolve: [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha)

Please read these notes!
