### ISSUE TITLE
ErrorAlert.js Enhancement

### ISSUE THREAD

**Issue by JonasJonny** [bartonhammond/snowflake#66]
At least for me "react-native-simpledialog-android" is not working in RN 0.20.
But could be simply replaced by https://facebook.github.io/react-native/docs/alert.html.

**Comment by bartonhammond** [comment]
I am working w/ the team to provide fix.  In the mean time, I created a temporary fix until they address it.  I like their solution as it encapsulates the difference.  If I don't get a fix soon, I'll look at swapping it out w/ your proposal.

Thanks!

**Comment by bartonhammond** [comment]
Fixed w/ [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha)
