### ISSUE TITLE
How can I get more details on why jest test runs are failing?

### ISSUE THREAD

**Issue by wookiem** [bartonhammond/snowflake#67]
My Parse User table has additional fields beyond the built-in username, password, email, emailVerified fields.  So, I've extended a number of files:
- profileInitialState.js
- profileReducer.js,
- LoginForm.js 
- profileFormValidation.js
- fieldValidation.js
- profileActions-test.js
- profileReducer-test.js

When I "npm run test" or "npm run test-chrome", all of the test cases are now failing.  

Prior to making the above changes, I had updated src/lib/config.js using the Parse keys to point to my database and I was able to successfully login using an existing user account.  I was also able to run clean test runs.

Any suggestions on how I can get jest to provide more verbose output so I can pin-point where it is failing.  I'm also hoping to setup breakpoints in chrome using "npm run test-chrome" so I can see  where the tests are failing.

Any help would be greatly appreciated!

**Comment by bartonhammond** [comment]
That's a great question which I have not an answer.  If you are on RN 20, I haven't moved there.

But if you are just getting no info on the command line it typically means there is a error.  What I do is isolate to one test case by providing the path to the test case.  And then I run it in debug mode.  Check the package . json  for the correct command.

**Comment by wookiem** [comment]
Thanks for the suggestions Barton.

Here's where I went wrong...  I git cloned snowflake to a local directory then used MacOS finder to copy over files and directories so I could integrate it into my existing project directory.  I ended up missing a bunch of hidden files:

.babelrc
.flowconfig
.gitignore
.tern-project
.watchmanconfig

Once I copied these over, test cases are now running clean.

**Comment by bartonhammond** [comment]
Good to hear!  Yeah, you need those files.
