### ISSUE TITLE
Use the react-native-router-flux@3.x.x

### ISSUE THREAD

**Issue by HellMagic** [bartonhammond/snowflake#77]
@bartonhammond hi, bartonhammond, firstly, i must to say the snowflake is an awesome project! thanks for that, thanks for all contributors!!!
i clone snowflake and use it in my project, i found it use the react-native-router-flux module, also an awesome project, but now the react-native-router-flux update to 3.x.x, and i replaced the 2.x.x in snowflake and modify some syntax, but it not work. i deep in the source code find the code structure changed a lot, en, so i just want to know if you have any idea to update the react-native-router-flux version in snowflake project, after all the new react-native-router-flux is better.
good luck, hope your reply~

**Comment by wookiem** [comment]
@bartonhammond @HellMagic

Looks like react-native-router-flux is still in beta and only works with React Native 0.22-rc.

**Comment by braco** [comment]
0.22 was just released - https://github.com/facebook/react-native/releases

**Comment by bartonhammond** [comment]
fixed w/ release [0.0.13](https://github.com/bartonhammond/snowflake/releases/tag/0.0.13)
