### ISSUE TITLE
undefined is not an object (evaluating 'StatusBar.barStyle=data.style')

### ISSUE THREAD

**Issue by ericpeters0n** [bartonhammond/snowflake#79]
After registering or logging in, 'Navigate to Subview' button renders this error.

**Comment by ericpeters0n** [comment]
<img width="376" alt="iphone_6s_-_iphone_6s___ios_9_2__13c75_" src="https://cloud.githubusercontent.com/assets/680307/13932738/d8000814-ef66-11e5-8855-9ee789e60a8a.png">

**Comment by bartonhammond** [comment]
Fix with release [0.0.13](https://github.com/bartonhammond/snowflake/releases/tag/0.0.13)
