### ISSUE TITLE
/react/redux/snowflake/src/snowflake.js: Unexpected token (120:6)

### ISSUE THREAD

**Issue by debianmaster** [bartonhammond/snowflake#85]
When i'm running from xcode i get following error.

```json
{
    "type": "TransformError",
    "message": "SyntaxError /Users/jjonagam/react/redux/snowflake/src/snowflake.js: Unexpected token (120:6)",
    "snippet": "\u001b[0m    \u001b[36mvar\u001b[39m color \u001b[1m=\u001b[22m \u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mprops\u001b[1m.\u001b[22mselected \u001b[1m?\u001b[22m \u001b[31m'#FF3366'\u001b[39m \u001b[1m:\u001b[22m \u001b[31m'#FFB3B3'\u001b[39m\u001b[1m;\u001b[22m\n    \u001b[36mreturn\u001b[39m \u001b[34m\u001b[1m(\u001b[22m\u001b[39m\n      \u001b[1m<\u001b[22mView style\u001b[1m=\u001b[22m\u001b[32m{\u001b[39m\u001b[32m{\u001b[39mflex\u001b[1m:\u001b[22m\u001b[35m1\u001b[39m\u001b[1m,\u001b[22m flexDirection\u001b[1m:\u001b[22m\u001b[31m'column'\u001b[39m\u001b[1m,\u001b[22m alignItems\u001b[1m:\u001b[22m\u001b[31m'center'\u001b[39m\u001b[1m,\u001b[22m alignSelf\u001b[1m:\u001b[22m\u001b[31m'center'\u001b[39m\u001b[32m}\u001b[39m\u001b[32m}\u001b[39m\u001b[1m>\u001b[22m\n        \u001b[1m<\u001b[22mIcon style\u001b[1m=\u001b[22m\u001b[32m{\u001b[39m\u001b[32m{\u001b[39mcolor\u001b[1m:\u001b[22m color\u001b[32m}\u001b[39m\u001b[32m}\u001b[39m name\u001b[1m=\u001b[22m\u001b[32m{\u001b[39m\u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mprops\u001b[1m.\u001b[22miconName\u001b[32m}\u001b[39m size\u001b[1m=\u001b[22m\u001b[32m{\u001b[39m\u001b[35m30\u001b[39m\u001b[32m}\u001b[39m \u001b[1m/\u001b[22m\u001b[1m>\u001b[22m\n        \u001b[1m<\u001b[22mText style\u001b[1m=\u001b[22m\u001b[32m{\u001b[39m\u001b[32m{\u001b[39mcolor\u001b[1m:\u001b[22m color\u001b[32m}\u001b[39m\u001b[32m}\u001b[39m\u001b[1m>\u001b[22m\u001b[32m{\u001b[39m\u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mprops\u001b[1m.\u001b[22mtitle\u001b[32m}\u001b[39m\u001b[1m<\u001b[22m\u001b[1m/\u001b[22mText\u001b[1m>\u001b[22m\n      \u001b[1m<\u001b[22m\u001b[1m/\u001b[22mView\u001b[1m>\u001b[22m\u001b[0m",
    "lineNumber": 120,
    "column": 6,
    "filename": "/Users/jjonagam/react/redux/snowflake/src/snowflake.js",
    "description": "/Users/jjonagam/react/redux/snowflake/src/snowflake.js: Unexpected token (120:6)",
    "errors": [{
        "description": "/Users/jjonagam/react/redux/snowflake/src/snowflake.js: Unexpected token (120:6)",
        "filename": "/Users/jjonagam/react/redux/snowflake/src/snowflake.js",
        "lineNumber": 120
    }]
}
```

**Comment by bartonhammond** [comment]
Be sure to kill whatever terminal is already running -ie, make sure to run "react-native start" in the correct window.  I had this same thing happen and it was because after updating Snowflake locally, there was a previous packager running.  After killing that packager and restarting it, iOS ran fine.

**Comment by nhatkhoa** [comment]
Please help me...
`64% 489/764[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/khoahoang/Desktop/snowflake/node_modules/immutable/dist/immutable.js" as it exceeds the max of "100KB".
72% 549/764Error while persisting cache: SyntaxError C:/Users/khoahoang/Desktop/snowflake/src/snowflake.js: Unexpected token (120:6)
`

**Comment by bartonhammond** [comment]
I'm not sure how to help w/ this.  I can't replicate it.

**Comment by asmalik107** [comment]
Out of the box, clean checkout, I see the same:

`START> request:/index.ios.bundle?platform=ios&dev=true
transforming [=========================               ] 62% 477/767[BABEL] Note: The code generator has deoptimised the styling of "/.../snowflake/node_modules/immutable/dist/immutable.js" as it exceeds the max of "100KB".
transforming [=============================           ] 72% 555/767Error while persisting cache: SyntaxError /.../snowflake/node_modules/react-native/Libraries/CustomComponents/Navigator/Navigation/NavigationEventEmitter.js: Unexpected token (33:5)`

**Comment by bartonhammond** [comment]
I will look at this tomorrow - today I have to take a trip.

**Comment by cport1** [comment]
I am also seeing this same error. 

I am also seeing the error src/components/FormButton.js: Unexpected token (47:6) on a fresh install when running from xcode.

**Comment by TheTekton** [comment]
I had this problem as well. If I'm not mistaken, just removing the .babelrc file fixed the persisting cache error. Before that, I also ran these lines, before removing the .babelrc file (just in case it matters, don't think it does):

`react-native upgrade`
`npm install ---save react`
`react-native upgrade`
`./node_modules/react-native/packager/packager.sh start --reset-cache`

`mv .babelrc .orig.babelrc`

**Comment by cport1** [comment]
Thank you @TheTekton this resolved the errors for me

**Comment by RumenTech** [comment]
Just removing .babelrc saved my day, thanks @TheTekton

**Comment by bartonhammond** [comment]
see [https://github.com/bartonhammond/snowflake/releases/tag/0.0.13b](https://github.com/bartonhammond/snowflake/releases/tag/0.0.13b)
