### ISSUE TITLE
Broken out of the box

### ISSUE THREAD

**Issue by austinksmith** [bartonhammond/snowflake#88]
Followed the setup instructions to a tee, the app refuses to run with the error that "snowflake" has not been registered, not sure what extra step is supposed to be involved here but this is the offending line

>   runApplication: function(appKey: string, appParameters: any): void {
    console.log(
      'Running application "' + appKey + '" with appParams: ' +
      JSON.stringify(appParameters) + '. ' +
      '__DEV__ === ' + String(__DEV__) +
      ', development-level warning are ' + (__DEV__ ? 'ON' : 'OFF') +
      ', performance optimizations are ' + (__DEV__ ? 'OFF' : 'ON')
    );
    invariant(
      runnables[appKey] && runnables[appKey].run,
      'Application ' + appKey + ' has not been registered. This ' +
      'is either due to a require() error during initialization ' +
      'or failure to call AppRegistry.registerComponent.'
    );
    runnables[appKey].run(appParameters);
  },

**Comment by bartonhammond** [comment]
Be sure you don't have another instance running: check your terminal windows - if Snowflake (or any React Native) app starts up and a instance of ```react-native start``` is running, you'll get this message.

**Comment by austinksmith** [comment]
Hmm, ok so i completely closed my terminal and restarted my emulator. My config looks like the following, 

```
module.exports = {
  backend: {
    parse: false,
    hapiRemote: false,
    hapiLocal: true
  },
  HAPI: {
    local: {
      url: 'http://127.0.0.1:5000'
    },
    remote: {
      url: 'https://mysnowflake-bartonhammond.rhcloud.com'
    }
  }
}
```

And the new error is now 
![screenshot 2016-04-11 16 27 55](https://cloud.githubusercontent.com/assets/2227747/14441346/64b5fc72-0002-11e6-8c9d-610354f2e3bc.png)

**Comment by bartonhammond** [comment]
Be sure to setup the ```src/lib/config.js``` file, see [https://github.com/bartonhammond/snowflake#setup](https://github.com/bartonhammond/snowflake#setup).  You have to either use the default Parse.com setup or run Hapi locally/OpenShift.

the ```config.js``` file can be copied from the ```config.example.js``` file in the same directory.

Notice the presence of the field ``` SESSION_TOKEN_KEY``` below of the ```config.example.js``` file.

```
module.exports = {
  PARSE: {
    APP_ID: '',
    REST_API_KEY: '',
    SESSION_TOKEN_KEY: 'SESSION_TOKEN_KEY'
  },
  backend: {
    parse: false,
    hapiRemote: true,
    hapiLocal: false
  }
}
```

**Comment by austinksmith** [comment]
Yeah i've done that, I posted my config.js contents above. Do i need to delete the example config file?

**Comment by bartonhammond** [comment]
Doh - my bad - trying to juggle too many things at once, and not very well.

It looks like ```AppAuthToken``` at [line 24](https://github.com/bartonhammond/snowflake/blob/master/src/lib/AppAuthToken.js#L24) expects the ```PARSE.SESSION_TOKEN_KEY``` in the constructor, even if the ```backend``` is hapi.

So try adding the following to your config.js

```
PARSE: {
    SESSION_TOKEN_KEY: 'SESSION_TOKEN_KEY'
  },
```

**Comment by bartonhammond** [comment]
You could put a conditional in that AppAuthToken and test for the backend.  If so, please create a PR, if you don't mind.

**Comment by sotojuan** [comment]
Don't want to make a new issue, but I got it running with the `remote` Hapi option but I cannot log in or sign up (requests fail). Is the `https://mysnowflake-bartonhammond.rhcloud.com` URL just fake? How can I set up a local Hapi server? Thanks for all your hard work?

**Comment by bartonhammond** [comment]
If you want to run the Hapi server, whether local or remote, see my companion project (which is referenced in the README.md) at [https://github.com/bartonhammond/snowflake-hapi-openshift](https://github.com/bartonhammond/snowflake-hapi-openshift)

It's much easier to setup the Parse.com solution for testing the mobile app, but if you want to "own" your server in order to test your code including the server code, the Hapi server is much better.

**Comment by bartonhammond** [comment]
And no, the ```https://mysnowflake-bartonhammond.rhcloud.com``` was there as an example - the name you use would be dependent upon how you setup the Hapi Server on OpenShift.

**Comment by austinksmith** [comment]
Looks like adding that config line resolved that problem, however there are some errors just navigating around in the android emulator.  Any extra guidance would be appreciated, thanks
![screenshot 2016-04-12 09 18 50](https://cloud.githubusercontent.com/assets/2227747/14461238/9f0d2c28-008f-11e6-80c4-c1108b02c540.png)

**Comment by bartonhammond** [comment]
I'm hoping someone will dive down on that...it has to be quite simple..

**Comment by bartonhammond** [comment]
Oh...I'm in hospital recovering from major surgery.  If you don't figure it out in a week I will try.

**Comment by austinksmith** [comment]
No problem, I'm probably going to just hold off and work on doing just android for now, I'll check later for any updates. Have a quick recovery

**Comment by bartonhammond** [comment]
Thanks.  You should have plenty to look at.

**Comment by bartonhammond** [comment]
Please close if resolved, @austinksmith

**Comment by austinksmith** [comment]
Not resolved, I simply didn't have the time to continue debugging so I'm taking a vanilla react native approach for now

**Comment by bartonhammond** [comment]
There's no problem w/ Snowflake though.  You are just needing to implement
a server solution which is well documented.

**Comment by austinksmith** [comment]
How does that not invalidate the advertised local functionality?

**Comment by bartonhammond** [comment]
You have to follow the instructions and take a couple of minutes to set up a server.  You have potions.

**Comment by CrashyBang** [comment]
@bartonhammond is it possible to add some logic so:
```
PARSE: {
    SESSION_TOKEN_KEY: 'SESSION_TOKEN_KEY'
},
```

Is not required if not using parse?

**Comment by bartonhammond** [comment]
If you want to fix that, please make a PR.  I am having multiple health issues, including cancer, and don't have the time or energy to do much w/ Snowflake.  But I will merge a PR if there is one so everyone can benefit.  Good luck.

**Comment by CrashyBang** [comment]
@bartonhammond will do, sorry to hear that hope you are on the mend!

**Comment by bartonhammond** [comment]
thanks for the effort and well wishes.  i will merge when ready.  please update the instructions as needed.  i appreciate much.
