### ISSUE TITLE
Profile form validation not working in profile edition view

### ISSUE THREAD

**Issue by sharq1** [bartonhammond/snowflake#89]
Inputs allow entering and sending invalid values, like username "Me", which causes `Bad request` response from server.

**Comment by bartonhammond** [comment]
Good catch!

**Comment by bartonhammond** [comment]
Fixed with [https://github.com/bartonhammond/snowflake/releases/tag/0.1.3](https://github.com/bartonhammond/snowflake/releases/tag/0.1.3)
