### ISSUE TITLE
Configure dev & prod mode

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#9]

**Comment by DanielMSchmidt** [comment]
We currently have a solution which is a bit hacky, but goes further than using __dev__ in order to have the possibility to switch between more than two states (e.g. TestFlight System). Would you be interested in seeing a PR?

**Comment by bartonhammond** [comment]
I have a issue for introducing a dev vs prod environment see #9.  We could use that.

Before going down the bunny hole w/ "a bit hackey" approach, could you explain what the approach is?  

I know I read somewhere that GitHub has a solution for storing project sensitive files for dev/prod, but I can't find it in the Help right now.  Before doing much w/ this topic, we need to research that option too.

If I understand correctly, TestFlight is a Apple App distribution solution.  It would be great if you could address the Bitrise.io Fastlane build to send the app there.  I don't have a specific issue for that right now.

It you have experience w/ building the native iOS app wrt certs, app ids, versioning, profiles and such, I could use help there too, see #24. 

Thanks for the offer of help! -barton

**Comment by DanielMSchmidt** [comment]
Well, this is #9, so I commented here ;) 

The original approach was to use babel's [plugin for inlining enviroment variables](https://github.com/babel/babel.github.io/blob/5.0.0/docs/usage/transformers/utility/inline-environment-variables.md) to replace every occurence of `process.env.NODE_ENV` with the word 'production', 'staging' or 'development'. This broke with the update to 0.16, as the packagers call to babel let the core of RN recompile where something like `'production' = __DEV__` was the result. (for more details see [this issue](https://github.com/facebook/react-native/issues/4232))

Nevertheless I think RN will soon fix their babel setup with the upgrade to babel 6 and this solution may be possible again. So far, our a bit hacky solition is that we use a shell script to string replace `process.env.NODE_ENV` with 'production', 'staging' or 'development' for just one file, which is then used to determine in which context the app is running and it works perfectly. No drawbacks, but as it is a workaround for a nicer solution I called id hacky. 

I will look into issue #24 and give my opinion on that topic, could you please write an issue for the TestFlight stuff you mentioned, I don't really know what you mean by that paragraph.

Have a nice day!

**Comment by bartonhammond** [comment]
Ok - i understand the concept of the script, makes sense.   I believe RN release 0.16 now has Babel 6: [https://github.com/facebook/react-native/releases/tag/v0.16.0](https://github.com/facebook/react-native/releases/tag/v0.16.0).  

It would be great to first upgrade snowflake to RN 0.16 and then use the Babel feature you mentioned, see #21 - I spent a little time on #21  and ran into issues getting iOS running in the simulator and dealing with the .bablerc / plugins / transformers etc.

**Comment by DanielMSchmidt** [comment]
Okay, if you did so, please inform me, I would like to add the env feature to the application ;)

**Comment by bartonhammond** [comment]
I am not working on the upgrade to RN 0.16 - I think I'll wait for the dust to settle a few more days.

**Comment by DanielMSchmidt** [comment]
Ah okay, well maybe I try it in a few days if I happen to have the time.

**Comment by bartonhammond** [comment]
Not going to address this.
