### ISSUE TITLE
Hot loading breaks the app

### ISSUE THREAD

**Issue by sharq1** [bartonhammond/snowflake#91]
App is stuck on `App` container.
Automatic redirection (from `/src/reducers/auth/authActions.js:244`) causes `Possible Unhandled Promise Rejection (id: 0): null is not an object (evaluating 'internalInstance.current...` warning:
![image](https://cloud.githubusercontent.com/assets/1241239/14816963/2e53c58e-0bb4-11e6-91fd-21218a79da8b.png)

When added button with link then on press I'm getting exception `null is not an object` as below:
![image](https://cloud.githubusercontent.com/assets/1241239/14816954/23d293d8-0bb4-11e6-9210-fdefc146469a.png)

**Comment by sharq1** [comment]
Looks like update to RN26 fixes this, hot reloading works now 👍

**Comment by siemiatj** [comment]
@bartonhammond looks like another good candidate for closing.

**Comment by bartonhammond** [comment]
Thanks for the heads up
