### ISSUE TITLE
Parse is gone, what will happen to backend?

### ISSUE THREAD

**Issue by varandpez** [bartonhammond/snowflake#93]
Hi, as you might already know Parse.com is stopping the serve and is open sourcing it soon. This means either we have to set up Parse engine locally or think about other alternatives. I personally don't like maintaining Parse engine locally and seeking similar technologies.

What are your thoughts on this?

Thanks.

**Comment by bartonhammond** [comment]
I've already provided a Hapi Server that runs locally and for free on Redhat OpenShift.  I will not do any other backends.  Please look at README for details.   As the Snowflake project was about learning React Native and Redux, I see no reason to create yet another backend.  The infrastructure is in place, namely BackendFactory.js if someone wants to do another backend.
