### ISSUE TITLE
Unable to resolve module buffer from assert.js

### ISSUE THREAD

**Issue by aamarcha** [bartonhammond/snowflake#98]
react-native-cli: 0.2.0
react-native: 0.24.0
Mac : 10.11.4

Hello this is the entire error : Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/buffer and its parent directories...

**Comment by jaimeagudo** [comment]
Look at https://github.com/facebook/react-native/issues/4968 @aamarcha

**Comment by smwoods** [comment]
I'm getting the same issue. I've tried everything in that thread numerous times

**Comment by jaimeagudo** [comment]
I just posted something @smwoods https://github.com/facebook/react-native/issues/4968#issuecomment-221130783

You might try my bumped version https://github.com/jaimeagudo/snowflake

**Comment by smwoods** [comment]
@jaimeagudo thanks, that actually got me past that error. I have a different error, but hopefully one I can solve. What did you change exactly?

**Comment by kinhbang89** [comment]
I also get the same error. I also tried all the instructions by these commands but none of them works for me 

`rm -rf node_modules && npm install `

` rm -fr $TMPDIR/react-* or node_modules/react-native/packager/packager.sh --reset-cache`

**Comment by mikeon** [comment]
I got the error with buffer when trying emulate with Genymotion: "Requiring unknown module "buffer". If you are sure the module is there, try restarting the packager or running "npm install".

**Comment by anton6** [comment]
Same issue as @mikeon

**Comment by anton6** [comment]
`npm i buffer` seemed to resolve the issue

**Comment by bartonhammond** [comment]
This seems to be fixed w/ the most recent release: [https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha](https://github.com/bartonhammond/snowflake/releases/tag/0.1.2-alpha)

Please read those release notes!
