### ISSUE TITLE
Redux boilerplate

### ISSUE THREAD

**Issue by aksonov** [bartonhammond/snowflake#99]
Great starter kit! I've been looking a lot to find some alternative to Redux to decrease a lot of boilerplate. Just checked your components and they are the same as mine (bulky `connect` statements within React components, numerous action string constants and 'switch' statements within reducers).

I've been working on large app and was not satisfied with a lot of redux boilerplate. 
Unfortunately i was not able to find elegant alternative and had to build own one based on Reactive Programming (yeah, React Native is reactive, but Redux doesn't). Could you check https://github.com/aksonov/react-native-reactive ? I believe it could fit into this starter kit perfectly and simplify it by 20-30%.

**Comment by bartonhammond** [comment]
Hi @aksonov - I agree with your assessment of Redux - it's a lot of boilerplate though you get a very testable solution of state management.  Please feel free create a fork and replace Redux w/ your solution.  

If I were start another project using React-Native, I would take a serious look at [https://mobxjs.github.io/mobx/getting-started.html](https://mobxjs.github.io/mobx/getting-started.html).

**Comment by aksonov** [comment]
@bartonhammond Thanks for suggestion! Mobx looks really impressive. Probably i will try to use mobx inside react-native-reactive as plugin, so user could choose.

**Comment by aksonov** [comment]
@bartonhammond Created https://github.com/aksonov/react-native-mobx and start using it in my project. Thanks again for mobx suggestion, looks even easier comparing to Calmm-JS. With React Native Router Flux MobX became much easier - no need to wrap each scene with `@observer`

**Comment by bartonhammond** [comment]
@aksonov Glad that was of help.
